package com.company;

public enum Ingredients {
    WATER, LEMON , BROWNSUGAR , COLDWATER, ICE ,LIMEADE , STRAWBERRY, LEMONJUICE, MINT, POMEGRANATESYRUP, LEMONSODA, CHERRYSYRUP,
    ROSEMARRYSYRUP, PINEAPPLEJUICE

}
